import pandas as pd
import numpy as np
from sys import argv
from getChunk import getChunk

atomType = "CA"
lead_time = 15
maxSeqlength = 5

wround = int(argv[1]) 
chunk = getChunk(wround)

fName = 'Generation_round' + str(wround) + '_15_32_5_' + str(chunk) + '.txt'
df = pd.read_csv(fName, sep=',', header=None, skiprows=3)
df2 = df.rename(columns={0: "Frames", 1: "Atom", 2: "X", 3: "Y", 4: "Z"})

nAtoms = sum(df2.Frames == df2.iloc[0]['Frames'])
print("Looks like number of atoms = ", nAtoms)
frameList = pd.unique(df2.Frames)
outName = 'Generation_round' + str(wround) + '_15_32_5_' + str(chunk) + '.xyz'
df3 = df2[['Frames', 'Atom', 'X', 'Y', 'Z']]

with open(outName, "w") as outputfile:
    for frame in frameList:
        outputfile.write(str(nAtoms) + "\n")
        outputfile.write(" generated by Chitrak\n")
        thisFrame = df3[df3.Frames == frame]
        thisCoods = np.array(thisFrame[['X', 'Y', 'Z']])
        for cood in thisCoods:
            x = str(cood)
            x2 = x.lstrip('[').rstrip(']\n') + "\n"
            outputfile.write("  " + atomType + "\t" + x2)

df4 = df2[['Frames', 'X', 'Y', 'Z']]
nFrames = int(df4.shape[0]/nAtoms)
Coordinates = np.zeros((nFrames, nAtoms, 3))
count = 0
for frame in frameList:
    thisFrame = df4[df4.Frames == frame]
    thisCoods = np.array(thisFrame[['X', 'Y', 'Z']])
    Coordinates[count] = thisCoods
    count += 1

outName2 = 'Generation_round' + str(wround) + '_15_32_5_' + str(chunk) + '.npy'
np.save(outName2, Coordinates)


